# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Add Messaging Serverkey
        run: echo "package com.ln.simplechat.api\n\nconst val BASE_URL = \"${{secrets.MESSAGING_SERVER_KEY}}\"" > /src/main/java/com/ln/simplechat/api/ServerKey.kt

      - name: Execute Gradle build
        run: ./gradlew assembleRelease
    
      - run: git log  --pretty=oneline | head -n 10 >> log.txt
          
